### ISSUE TITLE
it dont work

### ISSUE THREAD

**Issue by ajhenley** [kkneomis/cyber_data_maker#3]
unlab@ajiusvm:~/other/cyber_data_maker$ python simulator.py
Traceback (most recent call last):
  File "simulator.py", line 137, in <module>
    malicious_config["links"] = gen_links()
  File "simulator.py", line 84, in gen_links
    "url": gen_link(),
  File "simulator.py", line 66, in gen_link
    request = str(encodedBytes, "utf-8")
TypeError: str() takes at most 1 argument (2 given)

**Comment by kkneomis** [comment]
Thanks for reporting. Has a make a few small syntax fixes but it should be working now.
```
$ python simulator.py 
New config at config/changeme/simulated/company.json
New config at config/changeme/simulated/malicious.json
```
